version: '3'
services:
  spark-master:
    image: spearframework/spark-2.4:kubernetes
    container_name: spark-master
    restart: always
    ports:
      - 7077:7077
      - 8080:8080
    command: ["/bin/sh","/spark-master"]
  spark-worker_1:
    image: spearframework/spark-2.4:kubernetes
    container_name: spark-worker_1
    restart: always
    ports:
        - 8081:8081
    command: [ "/bin/sh","/spark-worker" ]
    depends_on:
      - spark-master
  spark-worker_2:
    image: spearframework/spark-2.4:kubernetes
    container_name: spark-worker_2
    restart: always
    ports:
      - 8082:8082
    command: [ "/bin/sh","/spark-worker" ]
    depends_on:
      - spark-master

