### creating Deployments for both master and worker for spark.This Will create 1 master and 3 Workers by default
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      component: spark-master
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      containers:
        - name: spark-master
          image: spearframework/spark-2.4:kubernetes
          command: [ "/bin/sh" ]
          args: [ "/spark-master" ]
          ports:
            - containerPort: 7077
            - containerPort: 8080
          resources:
            requests:
              cpu: 200m

---
## Creating services for spark-master and spark-web-ui
kind: Service
apiVersion: v1
metadata:
  name: spark-master
spec:
  ports:
    - port: 7077
      targetPort: 7077
  selector:
    component: spark-master

---

kind: Service
apiVersion: v1
metadata:
  name: spark-webui
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    component: spark-master


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      component: spark-worker
  template:
    metadata:
      labels:
        component: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: spearframework/spark-2.4:kubernetes
          command: [ "/bin/sh" ]
          args: ["/spark-worker"]
          ports:
            - containerPort: 8081
            - containerPort: 4040
          resources:
            requests:
              cpu: 200m
